### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by Bender250** [englerfa/Logging_Python#1]
Use some library for structured logging.

I imagine the log in the following format:

```json
{
	"name": "full.path",
	"arguments": [{
		"type": "int",
		"name": "foo",
		"value": "1"
	}, {
		"type": "char",
		"name": "bar",
		"value": "hello world"
	}],
	"return_type": "string",
	"return_value": "hello world 1"
}
```

You can use any library, standard or some structured logging one, we have currently no constraints. This can help: https://stackoverflow.com/questions/48170682/can-structured-logging-be-done-with-pythons-standard-library

**Comment by Bender250** [comment]
You also do not have to format it by your own. You can create a class/dictionary in this format, and use json library to format it for you.

**Comment by Bender250** [comment]
Ideally, leave both implementations - the current formatting and the json formatting. And you can think about way, how a developer can pass the callback for the logging for either structured, or unstructured logs. They you select the right format based on his preferences and you use the logging framework callback he provides you. Feel free to ask for more details on this task.

**Comment by englerfa** [comment]
Added time:
```
{
	"name": "full.path",
	"arguments": [{
		"type": "int",
		"name": "foo",
		"value": "1"
	}, {
		"type": "char",
		"name": "bar",
		"value": "hello world"
	}],
	"return_type": "string",
	"return_value": "hello world 1",
        "time": "2019-09-20 14:12:27"
}
```
